FROM python:3.12-slim-bookworm

WORKDIR /app

# Copy dependency files
COPY pyproject.toml ./

# Copy source code
COPY src/ ./src/

# Install the package and then uninstall it to keep only dependencies
RUN pip install . && pip uninstall -y src

COPY settings.toml ./
COPY .env ./

EXPOSE 8000

CMD ["python", "-m", "src.main"]
