[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.21.0",
    "lihil[standard,supabase]>=0.2.16",
    "sqlalchemy>=2.0.41",
]
