// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-axios';
import type { LoginGetTokenTokenPostData, LoginGetTokenTokenPostResponses, LoginGetTokenTokenPostErrors, GetUserMeGetData, GetUserMeGetResponses, GetUserMeGetErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login Get Token
 * Missing Description
 */
export const loginGetTokenTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginGetTokenTokenPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginGetTokenTokenPostResponses, LoginGetTokenTokenPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: 'json',
        url: '/token',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get User
 * Missing Description
 */
export const getUserMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserMeGetResponses, GetUserMeGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/me',
        ...options
    });
};